// <auto-generated />
namespace StoreApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class fe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fe));
        
        string IMigrationMetadata.Id
        {
            get { return "201912211249012_fe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
